image: openjdk:22-ea-21-slim-bullseye

stages:
  - sonar  
  - build
  - deploy

.deploy_gcp: &deploy_gcp_template
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts  
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml --substitutions=${SUBSTITUTIONS}

build:
  stage: build
  before_script:
    - cd application
    - chmod +x mvnw
  script:         
    - ./mvnw clean package -P remote
  artifacts:
    expire_in: 15 mins 
    paths:      
      - $CI_PROJECT_DIR/application/target/oauth2-authorization-server.jar

deployment_dev:
  variables:
    JAVA_ENV: 'development'
    ARTIFACT_NAME: 'oauth2-authorization-server.jar'
    MIN_INSTANCES: '0'
    MEMORY: '4Gi'
    CPU: '1'
    GCP_PROJECT_ID: 'om-dev-mbusa-webapp-n-zmva'
    API_APP_NAME: 'oauth2-as-dev'
    API_APP_REGION: 'us-central1'
    SVR_LESS_CONN: 'projects/om-n-vpc-ntgf/locations/us-central1/connectors/vpc-connector-us-central'
    SUBSTITUTIONS: '_MEMORY=$MEMORY,_CPU=$CPU,_MIN_INSTANCES=$MIN_INSTANCES,_SERVERLESS_CONNECTOR=$SVR_LESS_CONN,_APP_REGION=$API_APP_REGION,_APP_NAME=$API_APP_NAME,_PROJECT_ID=$GCP_PROJECT_ID,_JAVA_ENVIRONMENT=$JAVA_ENV,_ARTIFACT_NAME=$ARTIFACT_NAME'
  <<: *deploy_gcp_template    
  only:
    - develop
